In [3]:

import seaborn as sns

In [5]:

n_colors = 13
colors = sns.color_palette('husl', n_colors=n_colors)
_colors = [tuple(map(lambda x: int(x * 255), c))
                for c in colors]


In [7]:
labels = [
    'Toolbar',
    'Image',
    'Text',
    'Icon',
    'Text Button',
    'Input',
    'List Item',
    'Advertisement',
    'Pager Indicator',
    'Web View',
    'Background Image',
    'Drawer',
    'Modal',
]

In [13]:
import cv2
import numpy as np


for i, color in enumerate(_colors):
    img = np.full((100,100,3),color, dtype=np.uint8)
    img = cv2.cvtColor(img, cv2.COLOR_RGB2BGR)
    cv2.imwrite(f"labels/{labels[i]}.png", img)

In [11]:
from data.rico import Rico

In [1]:
from data.visily import Visily
dataset = Visily("train")

hi
mkdir
dome
hmm <generator object Path.glob at 0x7fb81a90ce40> data/dataset/visily/raw/children_data <class 'pathlib.PosixPath'>
0 BUTTON {}
1 CHART {'BUTTON': 0}
2 TABLE {'BUTTON': 0, 'CHART': 1}
3 TEXT {'BUTTON': 0, 'CHART': 1, 'TABLE': 2}
4 ICON {'BUTTON': 0, 'CHART': 1, 'TABLE': 2, 'TEXT': 3}
5 TABBAR_MENU {'BUTTON': 0, 'CHART': 1, 'TABLE': 2, 'TEXT': 3, 'ICON': 4}
6 CONTAINER {'BUTTON': 0, 'CHART': 1, 'TABLE': 2, 'TEXT': 3, 'ICON': 4, 'TABBAR_MENU': 5}
7 TEXTBOX {'BUTTON': 0, 'CHART': 1, 'TABLE': 2, 'TEXT': 3, 'ICON': 4, 'TABBAR_MENU': 5, 'CONTAINER': 6}
8 CHECKBOX {'BUTTON': 0, 'CHART': 1, 'TABLE': 2, 'TEXT': 3, 'ICON': 4, 'TABBAR_MENU': 5, 'CONTAINER': 6, 'TEXTBOX': 7}
9 IMAGE {'BUTTON': 0, 'CHART': 1, 'TABLE': 2, 'TEXT': 3, 'ICON': 4, 'TABBAR_MENU': 5, 'CONTAINER': 6, 'TEXTBOX': 7, 'CHECKBOX': 8}
10 HEADER_MENU {'BUTTON': 0, 'CHART': 1, 'TABLE': 2, 'TEXT': 3, 'ICON': 4, 'TABBAR_MENU': 5, 'CONTAINER': 6, 'TEXTBOX': 7, 'CHECKBOX': 8, 'IMAGE': 9}
11 SIDEBAR_MENU {'BUTTON': 0, 'C

Processing...1234


len 9455
xam


Done!


In [2]:
from data.rico import Rico
dataset = Rico("train")

hi
mkdir
dome


Processing...1234


0 Toolbar {}
1 Image {'Toolbar': 0}
2 Text {'Toolbar': 0, 'Image': 1}
3 Icon {'Toolbar': 0, 'Image': 1, 'Text': 2}
4 Text Button {'Toolbar': 0, 'Image': 1, 'Text': 2, 'Icon': 3}
5 Input {'Toolbar': 0, 'Image': 1, 'Text': 2, 'Icon': 3, 'Text Button': 4}
6 List Item {'Toolbar': 0, 'Image': 1, 'Text': 2, 'Icon': 3, 'Text Button': 4, 'Input': 5}
7 Advertisement {'Toolbar': 0, 'Image': 1, 'Text': 2, 'Icon': 3, 'Text Button': 4, 'Input': 5, 'List Item': 6}
8 Pager Indicator {'Toolbar': 0, 'Image': 1, 'Text': 2, 'Icon': 3, 'Text Button': 4, 'Input': 5, 'List Item': 6, 'Advertisement': 7}
9 Web View {'Toolbar': 0, 'Image': 1, 'Text': 2, 'Icon': 3, 'Text Button': 4, 'Input': 5, 'List Item': 6, 'Advertisement': 7, 'Pager Indicator': 8}
10 Background Image {'Toolbar': 0, 'Image': 1, 'Text': 2, 'Icon': 3, 'Text Button': 4, 'Input': 5, 'List Item': 6, 'Advertisement': 7, 'Pager Indicator': 8, 'Web View': 9}
11 Drawer {'Toolbar': 0, 'Image': 1, 'Text': 2, 'Icon': 3, 'Text Button': 4, 'Input': 5, 'Li

Done!


In [7]:
from torch_geometric.data import DataLoader
dataloader = DataLoader(dataset,
                        batch_size=1,
                        num_workers=4,
                        pin_memory=True,
                        shuffle=False)

/Users/duchbui/opt/miniconda3/envs/const_layout/lib/python3.8/site-packages/torch_geometric/deprecation.py:22: UserWarning: 'data.DataLoader' is deprecated, use 'loader.DataLoader' instead
  warnings.warn(out)


In [12]:
for data in dataloader:  
    print(data)
    break

DataBatch(
  x=[8, 4],
  y=[8],
  attr={
    name=[1],
    width=[1],
    height=[1],
    filtered=[1],
    has_canvas_element=[1]
  },
  batch=[8],
  ptr=[2]
)


In [14]:
from torch_geometric.utils import to_dense_batch
label_c, mask_c = to_dense_batch(data.y, data.batch)

In [15]:
label_c

tensor([[2, 2, 4, 1, 2, 1, 1, 2]])

In [16]:
mask_c

tensor([[True, True, True, True, True, True, True, True]])

In [19]:
data["x"]

tensor([[0.5000, 0.1227, 0.9028, 0.0698],
        [0.5000, 0.2019, 0.9028, 0.0594],
        [0.5000, 0.9122, 0.8250, 0.0702],
        [0.3420, 0.5274, 0.2674, 0.1610],
        [0.3420, 0.6459, 0.2674, 0.0318],
        [0.6580, 0.5274, 0.2674, 0.1610],
        [0.6580, 0.5274, 0.2674, 0.1610],
        [0.6580, 0.6459, 0.2674, 0.0318]])

In [24]:
data["ptr"]

tensor([0, 8])

In [22]:
data["attr"]["filtered"]

tensor([True])

In [18]:
!cp /Users/duchbui/Documents/Test/autoformat/const_layout/data/dataset/rico/raw/semantic_annotations/59811.json .

In [20]:
import torch

# Create tensors
a = torch.tensor([1, 2, 3, 4, 5])
b = torch.tensor([10, 20, 30, 40, 50])
condition = torch.tensor([True, False, True, False, True])

# Use torch.where
result = torch.where(condition, a, b)

print(result)

tensor([ 1, 20,  3, 40,  5])


In [37]:
import json
from pathlib import Path

import torch
from torch_geometric.data import Data

from data.base import BaseDataset


def append_child(element, elements):
    if "children" in element.keys():
        for child in element["children"]:
            elements.append(child)
            elements = append_child(child, elements)
    return elements


def normalize_type(element_type, labels):
    if "CHART" in element_type:
        return "CHART"

    if element_type == "BUTTON_GROUP":
        return "TAG"

    if "BUTTON" in element_type:
        return "BUTTON"

    if element_type in ["GROUP"]:
        return "CONTAINER"

    if element_type == "TEXTAREA":
        return "TEXTBOX"

    if element_type in ["ICON", "RATING", "AVATAR"]:
        return "ICON"

    if element_type == "RADIO":
        return "CHECKBOX"

    if element_type in ["TRIANGLE", "OVAL", "RECTANGLE", "DIVIDER", "SLIDER"]:
        return "SHAPE"

    if "SIDEBAR_MENU" in element_type:
        return "SIDEBAR_MENU"

    if element_type not in labels:
        return None

    return element_type


class Visily():
    labels = [
        "BUTTON",
        "CHART",
        "TABLE",
        "TEXT",
        "ICON",
        "TABBAR_MENU",
        "CONTAINER",
        "TEXTBOX",
        "CHECKBOX",
        "IMAGE",
        "HEADER_MENU",
        "SIDEBAR_MENU",
        "TAG",
        "SHAPE",
    ]

    def __init__(self, split="train", transform=None):
        # super().__init__("visily", split, transform)
        self._label2index = None
        pass

    def download(self):
        super().download()


    @property
    def label2index(self):
        if self._label2index is None:
            self._label2index = dict()
            for idx, label in enumerate(self.labels):
                print(idx, label, self._label2index)
                self._label2index[label] = idx
        return self._label2index

    def process(self):
        import os
        data_list = []
        raw_dir = "/Users/duchbui/Documents/Test/autoformat/const_layout/data/dataset/visily/raw/children_data/"
        for json_path in sorted(os.listdir("/Users/duchbui/Documents/Test/autoformat/const_layout/data/dataset/visily/raw/children_data")):
            if ".json" not in json_path:
                continue
            with open(raw_dir + json_path) as f:
                ann = json.load(f)

            for parent in ann:
                W, H = float(parent["width"]), float(parent["height"])

                elements = parent["children"]
                N = len(elements)
                # if N == 0 or 12 < N:
                #     continue

                boxes = []
                labels = []

                for element in elements:
                    # bbox
                    if "data" in element:
                        x1 = element["data"]["position"]["x"]
                        y1 = element["data"]["position"]["y"]

                        width = (
                            element["data"]["width"]
                            if "width" in element["data"] and element["data"]["width"] is not None
                            else 10
                        )
                        height = (
                            element["data"]["height"]
                            if "height" in element["data"] and element["data"]["height"] is not None
                            else 10
                        )
                        print(width, height)
                        xc = x1 + width / 2.0
                        yc = y1 + height / 2.0
                        b = [xc / W, yc / H, width / W, height / H]

                        # label
                        l = normalize_type(element["type"], labels)
                        if l is not None:
                            labels.append(self.label2index[l])
                            boxes.append(b)

                boxes = torch.tensor(boxes, dtype=torch.float)
                labels = torch.tensor(labels, dtype=torch.long)

                data = Data(x=boxes, y=labels)
                data.attr = {
                    "name": json_path,
                    "width": W,
                    "height": H,
                    "filtered": True,
                    "has_canvas_element": False,
                }
                data_list.append(data)

        # shuffle with seed
        generator = torch.Generator().manual_seed(0)
        indices = torch.randperm(len(data_list), generator=generator)
        data_list = [data_list[i] for i in indices]

        # train 85% / val 5% / test 10%
        N = len(data_list)
        s = [int(N * 0.85), int(N * 0.90)]
        torch.save(self.collate(data_list[: s[0]]), self.processed_paths[0])
        torch.save(self.collate(data_list[s[0] : s[1]]), self.processed_paths[1])
        torch.save(self.collate(data_list[s[1] :]), self.processed_paths[2])


In [38]:
dataset = Visily("train")

In [39]:
dataset.process()

1440 876
1176 564
960 536
1440 64
1440 560
1440 734
1440 395
1176 240
10 10
10 10
10 10
440 10
113 10
440 10
10 10
440 10
10 10
0 BUTTON {}
1 CHART {'BUTTON': 0}
2 TABLE {'BUTTON': 0, 'CHART': 1}
3 TEXT {'BUTTON': 0, 'CHART': 1, 'TABLE': 2}
4 ICON {'BUTTON': 0, 'CHART': 1, 'TABLE': 2, 'TEXT': 3}
5 TABBAR_MENU {'BUTTON': 0, 'CHART': 1, 'TABLE': 2, 'TEXT': 3, 'ICON': 4}
6 CONTAINER {'BUTTON': 0, 'CHART': 1, 'TABLE': 2, 'TEXT': 3, 'ICON': 4, 'TABBAR_MENU': 5}
7 TEXTBOX {'BUTTON': 0, 'CHART': 1, 'TABLE': 2, 'TEXT': 3, 'ICON': 4, 'TABBAR_MENU': 5, 'CONTAINER': 6}
8 CHECKBOX {'BUTTON': 0, 'CHART': 1, 'TABLE': 2, 'TEXT': 3, 'ICON': 4, 'TABBAR_MENU': 5, 'CONTAINER': 6, 'TEXTBOX': 7}
9 IMAGE {'BUTTON': 0, 'CHART': 1, 'TABLE': 2, 'TEXT': 3, 'ICON': 4, 'TABBAR_MENU': 5, 'CONTAINER': 6, 'TEXTBOX': 7, 'CHECKBOX': 8}
10 HEADER_MENU {'BUTTON': 0, 'CHART': 1, 'TABLE': 2, 'TEXT': 3, 'ICON': 4, 'TABBAR_MENU': 5, 'CONTAINER': 6, 'TEXTBOX': 7, 'CHECKBOX': 8, 'IMAGE': 9}
11 SIDEBAR_MENU {'BUTTON': 0, 'CHAR

AttributeError: 'Visily' object has no attribute 'collate'

In [4]:

from pathlib import Path

raw_dir  = Path("data/dataset/visily/raw") / "children_data"

for json_path in sorted(raw_dir.glob("*")):
    print(json_path)